name: 🚀 Build and Deploy WebGL

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:2023.1.0f1  # Use an appropriate Unity version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Unity Project
        run: |
          # Install dependencies for Unity build (if any)
          sudo apt-get update
          sudo apt-get install -y libunwind8 libssl1.0.0
          
      - name: Build Unity project
        run: |
          # Run Unity build command inside Docker container
          /opt/unity/Editor/Unity -batchmode -quit -projectPath $GITHUB_WORKSPACE -buildTarget WebGL -executeMethod BuildScript.PerformBuild -logFile
          
      - name: Instalar cliente FTP
        run: sudo apt-get install -y lftp
  
      - name: Subir archivos via FTP
        env:
          FTP_SERVER: ${{ secrets.FEROZO_USER }}.ferozo.com
          FTP_USERNAME: ${{ secrets.FEROZO_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        run: lftp -u "$FTP_USERNAME","$FTP_PASSWORD" -e "mirror -R --delete --verbose --parallel=20 --exclude-glob .git/ dist /public_html/game-builds/${PROJECT_NAME}; bye" ftp://$FTP_SERVER || true
