name: 🚀 Build and Deploy WebGL

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Unity
        run: |
          wget -O Unity.tar.xz https://download.unity3d.com/download_unity/f336aca0cab5/LinuxEditorInstaller/Unity-6000.0.28f1.tar.xz
          tar -xf Unity.tar.xz -C /opt/
          sudo chmod -R +x /opt/Unity

      - name: Build Unity project
        run: |
          /opt/Unity/Editor/Unity -batchmode -quit \
          -projectPath $GITHUB_WORKSPACE \
          -buildTarget WebGL \
          -executeMethod BuildScript.PerformBuild \
          -logFile build.log

      - name: Instalar cliente FTP
        run: sudo apt-get install -y lftp
  
      - name: Subir archivos via FTP
        env:
          FTP_SERVER: ${{ secrets.FEROZO_USER }}.ferozo.com
          FTP_USERNAME: ${{ secrets.FEROZO_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        run: lftp -u "$FTP_USERNAME","$FTP_PASSWORD" -e "mirror -R --delete --verbose --parallel=20 --exclude-glob .git/ dist /public_html/game-builds/${PROJECT_NAME}; bye" ftp://$FTP_SERVER || true
