name: 🚀 Build and Deploy WebGL

on:
  release:
    types:
      - published

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Unity (using a Unity setup action)
      - name: Setup Unity
        uses: game-ci/unity-action@v2
        with:
          version: 2023.1.0f1  # TODO : Chequear la versión que necesitamos pa que corra piola
          personal: true
          
      # Step 3: Build the WebGL project using Unity CLI
      - name: Build WebGL Project
        run: |
          unity -batchmode -nographics -quit -projectPath . -buildTarget WebGL -executeMethod BuildScript.PerformBuild -logFile ./build.log

      # Step 4: Upload WebGL build to FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FEROZO_USER }}.ferozo.com
          username: ${{ secrets.FEROZO_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./Builds/WebGL  # The folder where Unity outputs the WebGL build
          remote-dir: /public_html/game-builds/${{ secrets.PROJECT_NAME }}
          clean: true
