name: 🚀 Build and Deploy WebGL

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:2023.1.0f1  # Use an appropriate Unity version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Unity Project
        run: |
          # Install dependencies for Unity build (if any)
          sudo apt-get update
          sudo apt-get install -y libunwind8 libssl1.0.0
          
      - name: Build Unity project
        run: |
          # Run Unity build command inside Docker container
          /opt/unity/Editor/Unity -batchmode -quit -projectPath $GITHUB_WORKSPACE -buildTarget WebGL -executeMethod BuildScript.PerformBuild -logFile
          
      - name: Upload WebGL build to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FEROZO_USER }}.ferozo.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./Builds/WebGL
          remote-dir: /public_html/game-builds/${{ github.repository }}
